# Generated by Django 5.2.7 on 2025-10-19 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_crud_operations', '0002_payment_alter_post_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'managed': False},
        ),
    ]
